import { StorageSchema } from './type';

export const DEFAULT_CONFIG: StorageSchema = {
  primarySubtitle: {
    enabled: true,
    language: 'en',
    positionReference: 'bottom',
    positionOffset: 180,
    color: '#ffffff',
    fontSize: 6,
    fontWeight: 4,
    backgroundOpacity: 0,
    lineBreak: true,
  },
  secondarySubtitle: {
    enabled: true,
    language: 'ko',
    positionReference: 'bottom',
    positionOffset: 100,
    color: '#ffffff',
    fontSize: 4,
    fontWeight: 2,
    backgroundOpacity: 0,
    lineBreak: false,
  },
  videoSkip: {
    enabled: true,
    forward: 'ArrowRight',
    backward: 'ArrowLeft',
    skipTime: 1,
    skipTimeUnit: 'subtitles',
    fallbackTime: 5,
    fallbackUnit: 'seconds',
  },
  subVideoSkip: {
    enabled: false,
    forward: '',
    backward: '',
    skipTime: 10,
    skipTimeUnit: 'seconds',
    fallbackTime: 10,
    fallbackUnit: 'seconds',
  },
  shortcuts: {
    enabled: false,
    savePrimary: '',
    saveSecondary: '',
    togglePrimary: '',
    toggleSecondary: '',
  },
  loop: {
    enabled: false,
    toggleLoop: '',
    startPoint: '',
    endPoint: '',
    loopCurrentSubtitle: '',
    playCurrentSubtitleOnce: '',
  },
  playbackSpeed: {
    enabled: false,
    increase: '',
    decrease: '',
    reset: '',
  },
};
